services:
  database:
    image: "postgres:15.3"
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toppassword
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "3001:5432"
    restart: always
  app:
    build: "."
    ports:
      - "80:3000"
    restart: always
    depends_on:
      - database